services:
  db:
    image: mysql:8.0
    container_name: vision-reader-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vision-reader-db
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql:/var/lib/mysql

  backend:
    image: node:20
    container_name: vision-reader-backend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/vision-reader-db
    command: >
      sh -c "
        npm install &&
        npm run prisma:migrate &&
        npm run dev
      "
volumes:
  mysql_data:
